FROM	mariadb

# FROM    debian:buster

# LABEL   maintainer=${INTRANAME}

# RUN     apt-get update &&\
#         apt install -y \
#         apt-utils \
#         apt-utils \
#         mariadb-server \
#         mariadb-client

# # the default port for mariadb
# EXPOSE 3306