version: "3"  # without specifying version it complains about unsupported config options.
services:
  
  mariadb:
    # build: ./requirements/mariadb
    # image: mariadb
    #example uses: 'image: mysql:8.0', not mariadb
    image: mysql:8.0
    container_name: mariadb
    env_file: .env
    environment:
      MYSQL_DATABASE: wordpress
    # Below was lifted from Wordpress Dockerhub example (except db was built on mysql5.7)
    restart: always 
    #Just taken from the example on Dockerhub
    # relies on mysql not mariadb:
    volumes:
     - mariadb:/var/lib/mysql
    # not using this network, or defining our own custom one.
    networks:
      - app-network
    command: '--default-authentication-plugin=mysql_native_password'
  
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    # ports:
    #   - 8080:80
    links: #Should be like depends_on but with extra addressability?
      - mariadb:3306
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: mysql_usr
      WORDPRESS_DB_PASSWORD: iamusr
      WORDPRESS_DB_NAME: wordpress
      # WORDPRESS_DB_HOST: $${DB_HOST}
      # WORDPRESS_DB_NAME: $${DB_NAME}
      # WORDPRESS_DB_USER: $${MYSQL_USER}
      # WORDPRESS_DB_PASSWORD: $${MYSQL_PASSWORD}
    restart: always
    volumes:
      - wordpress:/var/www/html
    # not using this network, or defining our own custom one.
    networks:
      - app-network
  
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "80:80" #Temporarily allowing access to nginx through port 80 (http) before certs have been set up.
      - "443:443"
    links:
      - wordpress:9000
    env_file: .env
    environment:
      NGINX_HOST: limartin.42.fr #Trying a different syntax
      NGINX_PORT: 80
      # - NGINX_HOST=limartin.42.fr #From nginx docker hub
      # - NGINX_PORT=80
    restart: always
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - wordpress:/var/www/html #Mounts wordpress to dir set as root in nginx server block
      - certbot-etc:/etc/letsencrypt
    # not using this network, or defining our own custom one.
    networks:
      - app-network
      
      # Your NGINX container must be the only entrypoint into your
      # infrastructure via the port 443 only, using the TLSv1.2 or TLSv1.3
      # protocol.

# THIS ENTIRE SERVICE WILL NOT BE INCLUDED OUTSIDE FOLLOWING ALONG WITH THE TUTORIAL:
  certbot:
    depends_on:
      - mariadb
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email limartin@student.codam.nl --agree-tos --no-eff-email --staging -d limartin.42.fr -d www.limartin.42.fr

volumes:
  certbot-etc:
  wordpress:
  mariadb:

networks:
  app-network:
    driver: bridge

# TEMPLATE:
# services:
#   web:
#     build: .
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/code
#       - logvolume01:/var/log
#     links:
#       - redis
#   redis:
#     image: redis
# volumes:
#   logvolume01: {}
