version: "3"  # without specifying version it complains about unsupported config options.
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
# volumes:


# TEMPLATE:
# services:
#   web:
#     build: .
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/code
#       - logvolume01:/var/log
#     links:
#       - redis
#   redis:
#     image: redis
# volumes:
#   logvolume01: {}
