version: "3"  # without specifying version it complains about unsupported config options.
services:
  
  mariadb:
    # build: ./requirements/mariadb
    # image: mariadb
    #example uses: 'image: mysql:8.0', not mariadb
    image: mysql:8.0
    env_file: .env
    environment:
      MYSQL_DATABASE: wordpressdb # Below was lifted from Wordpress Dockerhub example (except db was built on mysql5.7)
    restart: always #Just taken from the example on Dockerhub
    # relies on mysql not mariadb:
    # volumes:
    #  - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    # not using this network, or defining our own custom one.
    # networks:
    #   - app-network
  
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    # ports:
    #   - 8080:80
    links: #Should be like depends_on but with extra addressability?
      - mariadb:3306
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_DB_USER: $${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: $${MYSQL_PASSWORD}
    restart: always
    #volumes:
     #- wordpress:/var/www/html
  
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - "80:80" #Temporarily allowing access to nginx through port 80 (http) before certs have been set up.
      - "443:443"
    links:
      - wordpress:9000
    env_file: .env
    environment:
      NGINX_HOST: limartin.42.fr #Trying a different syntax
      NGINX_PORT: 80
      # - NGINX_HOST=limartin.42.fr #From nginx docker hub
      # - NGINX_PORT=80
    restart: always
      
      # Your NGINX container must be the only entrypoint into your
      # infrastructure via the port 443 only, using the TLSv1.2 or TLSv1.3
      # protocol.

volumes:
  wordpress:
  mariadb:


# TEMPLATE:
# services:
#   web:
#     build: .
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/code
#       - logvolume01:/var/log
#     links:
#       - redis
#   redis:
#     image: redis
# volumes:
#   logvolume01: {}
