version: "3"  # without specifying version it complains about unsupported config options.
services:
  
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - "80:80" #Temporarily allowing access to nginx through port 80 (http) before certs have been set up.
      - "443:443"
    links:
      - wordpress
    restart: always
      
      # Your NGINX container must be the only entrypoint into your
      # infrastructure via the port 443 only, using the TLSv1.2 or TLSv1.3
      # protocol.
  
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    # ports:
    #   - 8080:80
    links: #Should be like depends_on but with extra addressability?
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    restart: always
    #volumes:
     #- wordpress:/var/www/html
  
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example #This needs to change to env variable
      MYSQL_DATABASE: exampledb # Below was lifted from Wordpress Dockerhub example (except db was built on mysql5.7)
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    restart: always #Just taken from the example on Dockerhub
    #volumes:
     #- db:/var/lib/mysql

volumes:
  wordpress:
  mariadb:


# TEMPLATE:
# services:
#   web:
#     build: .
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/code
#       - logvolume01:/var/log
#     links:
#       - redis
#   redis:
#     image: redis
# volumes:
#   logvolume01: {}
